import { HttpResponse, http } from 'msw'

export const MOCK_IMAGE_BYTES = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
  'base64',
)

export type ProviderRequest = {
  provider: 'openai' | 'gemini'
  endpoint: string
  body: unknown
}

export const providerRequests: Array<ProviderRequest> = []

export function resetProviderRequests() {
  providerRequests.length = 0
}

const openAiResponse = () =>
  HttpResponse.json({
    created: 1_700_000_000,
    data: [{ b64_json: MOCK_IMAGE_BYTES.toString('base64') }],
  })

export const providerHandlers = [
  http.post(
    'https://api.openai.com/v1/images/generations',
    async ({ request }) => {
      providerRequests.push({
        provider: 'openai',
        endpoint: new URL(request.url).pathname,
        body: await request.json(),
      })
      return openAiResponse()
    },
  ),

  http.post('https://api.openai.com/v1/images/edits', async ({ request }) => {
    const formData = await request.formData()
    providerRequests.push({
      provider: 'openai',
      endpoint: new URL(request.url).pathname,
      body: Object.fromEntries(
        Array.from(formData.entries(), ([key, value]) => [
          key,
          typeof value === 'string'
            ? value
            : { name: value.name, size: value.size, type: value.type },
        ]),
      ),
    })
    return openAiResponse()
  }),

  http.post(
    'https://generativelanguage.googleapis.com/v1beta/models/:model\\:generateContent',
    async ({ params, request }) => {
      providerRequests.push({
        provider: 'gemini',
        endpoint: new URL(request.url).pathname,
        body: await request.json(),
      })
      return HttpResponse.json({
        candidates: [
          {
            content: {
              role: 'model',
              parts: [
                { text: `Mock image generated by ${String(params.model)}` },
                {
                  inlineData: {
                    mimeType: 'image/png',
                    data: MOCK_IMAGE_BYTES.toString('base64'),
                  },
                },
              ],
            },
            finishReason: 'STOP',
          },
        ],
      })
    },
  ),
]
